### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by llacroix** [melvinzhang/scheme2llvm#1]
Have you considered extending the compiler? As far as I know, the compiler works fine. It's quite fast on my computer. Far from the 20seconds compile time for bootstrapping. I'm currently working on a much more structured compiler on my free time.

I see you didn't work on it for already 2 years so I guess you just don't have time for this project. Anyhow, it is pretty interesting. Thank you!

**Comment by melvinzhang** [comment]
@llacroix thanks for your interest in this project, I've no intention to develop this further as the current supported subset is very minimal, just enough to write a compiler. 

The original goal for starting on this is to gain experience using LLVM to generate native code. With the aim to write a LLVM backend for Maru, which I think is a much more interesting Lisp. 

See http://piumarta.com/software/maru/ and https://github.com/melvinzhang/maru
