### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by michelp** [melvinzhang/scheme2llvm#2]
Is there a license for this work?

**Comment by melvinzhang** [comment]
The code is derived from https://web.archive.org/web/20111220233738/http://www.ida.liu.se/~tobnu/scheme2llvm/compile.ss.heap which as far as I know does not have an explicit license. I'd be happy to license my contributions under the MIT license.

**Comment by michelp** [comment]
The page on the right on that link says "Well, BSD license." which I take to mean all the works linked to on that page.  The the 2-clause form I guess is almost identical to MIT.  Maybe put both licenses in a LICENSE file specify MIT for your contributions?  Very interesting looking project!

**Comment by melvinzhang** [comment]
Good point, I never noticed that before. I've added the BSD license, also using it for my additions since it would be messy to put mine under a different licence.

**Comment by melvinzhang** [comment]
@michelp do you plan to use this in some way?

**Comment by michelp** [comment]
Looking for an IR generator to play with the nvidia NVVM IR for generating CUDA kernels to run on GPUs.  There's an old paper by Daniel Hillis that describes a very simple but powerful parallel lisp syntax that I think would map nicely to CUDA:

 https://pdfs.semanticscholar.org/0a86/be8e1f4dc7942d4c6b113eea8a9434a45702.pdf

**Comment by melvinzhang** [comment]
Nice, and thanks for the link to the paper. Btw, you should also checkout https://github.com/dubek/malc
